parameters:
  azureSubscription: "acrserviceconnectionmanuall"

jobs:
- job: Terraform
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self

  - task: AzureCLI@2
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        pwsh terraform_conditional_run.ps1