stages:
- stage: TerraformStageStart
  jobs:
  - job: Terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'acrserviceconnectionmanuall'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          pwsh terraform_conditional_run.ps1