# stages:
# - stage: TerraformStageStart
#   jobs:
#   - job: Terraform
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - checkout: self

#     - task: UsePythonVersion@0
#       inputs:
#         versionSpec: '3.x'
#         addToPath: true

#     - task: AzureCLI@2
#       inputs:
#         azureSubscription: 'acrserviceconnectionmanuall'
#         scriptType: 'pscore'
#         scriptLocation: 'inlineScript'
#         inlineScript: |
#           pwsh terraform_conditional_run.ps1

parameters:
  - name: ContinueEvenIfResourcesAreGettingDestroyed
    type: boolean
    default: false
  - name: AzureSubscription
    type: string

steps:

  - task: AzureCLI@2
    displayName: "terraformdeploy"
    name: TerraformDeploy
    inputs:
      azureSubscription: "acrserviceconnectionmanuall"
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
            az --version
            pwsh terraform_conditional_run.ps1 -deploymentResourceGroupName "testexample-resources-vin" -deploymentStorageAccountName "teststorageaccount12345v" -workSpace $(Environment) -continueEvenIfResourcesAreGettingDestroyed ${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }} -terraformJsonOutputFile $(Pipeline.Workspace)/terraformartifact/terraform_output.json
      # azureSubscription: 'acrserviceconnectionmanuall'
      # targetType: filePath
      # filePath: '$(Pipeline.Workspace)/terraformartifact/terraform_conditional_run.ps1'
      # arguments: '-deploymentResourceGroupName $(DeploymentResourceGroupName) -deploymentStorageAccountName $(DeploymentStorageAccountName) -workSpace $(Environment) -continueEvenIfResourcesAreGettingDestroyed $${{ parameters.ContinueEvenIfResourcesAreGettingDestroyed }} -terraformJsonOutputFile $(Pipeline.Workspace)/terraformartifact/terraform_output.json'