name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  Terraform:
    runs-on: ubuntu-latest

    parameters:
      azureSubscription: "acrserviceconnectionmanuall"

    steps:
      - checkout: self

      - task: AzureCLI@2
        inputs:
          azureSubscription: ${{ jobs.Terraform.parameters.azureSubscription }}
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            pwsh terraform_conditional_run.ps1